### PR TITLE
Update to DCA v23.1.2

### LINKED ISSUE #47: Turn off Data Dashboard in production
our update to https://github.com/Sage-Bionetworks/data_curator/releases/tag/v22.11.3 turns on the data dashboard.

I imagine this will result in quite a few questions from centers about data completeness. I have some already.

I would like to explore the possibility of hiding the data daashboard in production until there is appropriate documentation for centers and we can properly launch the feature at a steering committee.

I would like to remove ASAP and then target adding back in during the 23/01 sprint.

### PR DESCRIPTION
**Pull request by adamjtaylor**
This PR gets us level with the `main` branch of the Sage-Bionetworks/data_curator repo, which at the time of the PR is level with DCA v23.1.2.

This turns off the data dashboard by default (Fixes #47) and updates the method of Google sheets authentication

### CODE REVIEW

**Comment by adamjtaylor** [comment]
@elv-sb looks like we have some conflicts that need resolution beyond what the web UI can do - will try and do this early next week.

**Comment by adamjtaylor** [comment]
Hi @afwillia. Would you be able to take a look at this PR to update us to v23.1.2? It looks like there are some conflicts that need resolution beyond what Github can display. Many thanks in advance (cc @milen-sage)

**Review by afwillia — APPROVED** [review]
These changes look good to me. Let's see if those conflicts cause an issue if I approve this.

**Comment by afwillia** [comment]
Looks like no. I'll take some time to resolve those conflicts.

**Comment by afwillia** [comment]
@adamjtaylor hey I fixed the merge conflicts in the three files that were updated to disable the dashboard. Are you able to add those updates here?

**Comment by adamjtaylor** [comment]
The deployment to staging kicked off by merging this PR seemed to complete

But the app is unresponsive
Screenshot 2023-01-31 at 18 01 02



Shiny logs seem to show that it fails with the error `Unable to open file 'functions/metadataModel.py' (does it exist?)`

Did we miss something @afwillia @milen-sage?

```
2023-01-31T17:54:45.422067+00:00 shinyapps[5750996]: Starting R with process ID: '655'
2023-01-31T17:54:45.422449+00:00 shinyapps[5750996]: Shiny application starting ...
2023-01-31T17:54:48.359327+00:00 shinyapps[5750996]: Error in eval(exprs, envir) : 
2023-01-31T17:54:48.359368+00:00 shinyapps[5750996]:   Unable to open file 'functions/metadataModel.py' (does it exist?)
2023-01-31T17:54:48.359374+00:00 shinyapps[5750996]: Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
2023-01-31T17:54:48.359380+00:00 shinyapps[5750996]: Execution halted
2023-01-31T17:54:48.359399+00:00 shinyapps[5750996]: Shiny application exiting ...
```

**Comment by afwillia** [comment]
@adamjtaylor that's strange but seems related to other issues I've been seeing. I'm looking into it now.

**Comment by adamjtaylor** [comment]
Thank you @afwillia! I've opened a service desk ticket here to ensure it is prioritised: https://sagebionetworks.jira.com/servicedesk/customer/portal/5/IBCSPRT-131?created=true

**Comment by adamjtaylor** [comment]
With the fix introduced in #66 this has now been solved and is deployed to staging

**Pull request merged**
