### PR TITLE
Update to DCA v22.11.3

### PR DESCRIPTION
**Pull request by rrchai**
- Reverts ncihtan/HTAN-data-curator#59 to be back fetching the upstream

I will look into where the issues come from.

### CODE REVIEW

**Comment by rrchai** [comment]
By testing this branch, the dashboard can be successfully launched locally using the latest release of `schematic`.
Screen Shot 2022-12-08 at 2 30 21 AM

But it failed to load using the latest `develop` branch of `schematic`.

**Comment by rrchai** [comment]
✅  Just tested with the latest `release` of schematic in shinyapps.io - the dashboard can be rendered.

I think it might be a bug from the backend. Here is what might cause the error. 

The dashboard is expecting "errors" and "warnings" two outputs from the validation results, where "warnings" should return the cross-manifest check results with certain format. However, using the latest `develop` of `schematic`, one(s) of manifests have invalid **errors** from "warnings" output, which makes the app crashed. For example:
```console
synapse get syn24994554  
schematic model -c schematic_config.yml validate -mp synapse_storage_manifest.csv -dt Diagnosis -rr

warning: For the attribute 'AJCC Clinical T', on row 4, 1670472942462 is not one of ['T2a1', 'T3b', 'T1b1', 'T2a2', 'T1', 'T2b', 'T2', 'Ta', "Tis (Paget's)", 'Tis', 'T2a', 'TX', 'T1a1', 'T2c', 'T4a', 'T1a2', 'T2d', 'T4e', 'Tis (LCIS)', 'T0', 'T1c', 'T3', 'T3d', 'T4b', 'T4', 'Tis (DCIS)', 'unknown', 'T1mi', 'Not Reported', 'T3c', 'T3a', 'T1a', 'T4d', 'T4c', 'T1b', 'T1b2', ''].
warning: For the attribute 'AJCC Pathologic T', on row 4, 1670472942789 is not one of ['T2a1', 'T3b', 'T1b1', 'T2a2', 'T1', 'T2b', 'T2', 'Ta', "Tis (Paget's)", 'Tis', 'T2a', 'TX', 'T1a1', 'T2c', 'T4a', 'T1a2', 'T2d', 'T4e', 'Tis (LCIS)', 'T0', 'T1c', 'T3', 'T3d', 'T4b', 'T4', 'Tis (DCIS)', 'unknown', 'T1mi', 'Not Reported', 'T3c', 'T3a', 'T1a', 'T4d', 'T4c', 'T1b', 'T1b2', ''].
warning: For the attribute 'AJCC Clinical T', on row 6, 1667884542480 is not one of ['T2a1', 'T3b', 'T1b1', 'T2a2', 'T1', 'T2b', 'T2', 'Ta', "Tis (Paget's)", 'Tis', 'T2a', 'TX', 'T1a1', 'T2c', 'T4a', 'T1a2', 'T2d', 'T4e', 'Tis (LCIS)', 'T0', 'T1c', 'T3', 'T3d', 'T4b', 'T4', 'Tis (DCIS)', 'unknown', 'T1mi', 'Not Reported', 'T3c', 'T3a', 'T1a', 'T4d', 'T4c', 'T1b', 'T1b2', ''].
warning: For the attribute 'AJCC Pathologic T', on row 6, 1667884542807 is not one of ['T2a1', 'T3b', 'T1b1', 'T2a2', 'T1', 'T2b', 'T2', 'Ta', "Tis (Paget's)", 'Tis', 'T2a', 'TX', 'T1a1', 'T2c', 'T4a', 'T1a2', 'T2d', 'T4e', 'Tis (LCIS)', 'T0', 'T1c', 'T3', 'T3d', 'T4b', 'T4', 'Tis (DCIS)', 'unknown', 'T1mi', 'Not Reported', 'T3c', 'T3a', 'T1a', 'T4d', 'T4c', 'T1b', 'T1b2', ''].
```

**Comment by rrchai** [comment]
✅  Just tested with the latest `release` of schematic in shinyapps.io, the dashboard can be rendered.

**Comment by adamjtaylor** [comment]
@rrchai is it OK for this PR to be closed?

**Comment by rrchai** [comment]
@adamjtaylor Thanks for reminding!
Close as it's out of date.

**Pull request closed without merging**
