### PR TITLE
Change python file from metadataModel.py to metadata_model.py to matc…

### PR DESCRIPTION
**Pull request by afwillia**
…h file in functions directory.

### CODE REVIEW

**Comment by afwillia** [comment]
The python script `functions/metadata_model.py` was recently renamed to `functions/metadataModel.py` and somehow this last sync updated the filename, but not how it was referenced in the app. This updates ensures the filenames are consistent across the app.

**Comment by afwillia** [comment]
The deployment workflow failed because it's deploying to the testing instance which uses the develop branch of schematic. Currently that does not support python 3.8. However, the staging instance of DCA uses PyPy schematic which still supports python 3.8

**Review by adamjtaylor — APPROVED** [review]

**Comment by adamjtaylor** [comment]
Thanks @afwillia - so if I understand correctly I can merge this now, despite the failed deployment on the branch?

**Comment by afwillia** [comment]
@adamjtaylor correct! Thank you.

**Comment by adamjtaylor** [comment]
Confirming that that has deployed to staging correctly! Thank you @afwillia

**Pull request merged**
