### PR TITLE
Update DCA from upstream to be level with v23.3.1

### LINKED ISSUE #68: Update DCA to include HTAN-163 fix
[HTAN-163](https://sagebionetworks.jira.com/browse/HTAN-163) requires a fix in DCA.
This issue is to track its deployment in the HTAN DCA instance
@milen-sage to confirm when this is released in the upstream repo.

### PR DESCRIPTION
**Pull request by adamjtaylor**
This PR updates HTANs DCA to fix #68 

* Develop no poetry (#477)

* Set instance size to xxxlarge and log level to verbose during app deploy.

* Only install schematic from pip, never use develop branch.

* configureApp() will fail if the app does not exist yet. Put after deployApp() in case of first deployment.

* try setting upload to FALSE and then configure it. The configApp() fails after deployApp()

* if app exists, configure then deploy. Otherwise, deploy then configure.

* change appName to testingXXX so it creates a new app instance and tests if the rsconnect configuration logic works.

* Logic worked, go back to testing1 name

* coerce warning to character so strsplit() does not fail. (#520)

---------

### CODE REVIEW

**Review by afwillia — APPROVED** [review]
This will resolve the validation hang up issue.

**Comment by afwillia** [comment]
RE the merge conflict, keep
```
          echo Installing pypi version of schematic
          git clone --single-branch --branch main https://github.com/Sage-Bionetworks/schematic.git
          cp schematic_config.yml schematic/config.yml
          pip3 install schematicpy
```

and discard

```
          # use 'poetry' to install schematic dev schematic
          # If commit is tagged for release or in main branch, install schematic from pypi
          if [[ $GITHUB_REF_NAME == v*.*.* ]] || [[ $GITHUB_REF_NAME == main ]]; then
            echo Installing pypi version of schematic
            git clone --single-branch --branch main https://github.com/Sage-Bionetworks/schematic.git
            cp schematic_config.yml schematic/config.yml
            cd schematic
            pip3 install schematicpy
          else
            pip3 install poetry
            echo Installing develop branch of schematic from github
            git clone --single-branch --main develop https://github.com/Sage-Bionetworks/schematic.git
            cp schematic_config.yml schematic/config.yml
            cd schematic
            poetry build
            pip3 install dist/schematicpy-*-py3-none-any.whl
          fi
```

The reason is because schematic installed from github requires python 3.9+ which is incompatible with shinyapps.io.

**Comment by afwillia** [comment]
@adamjtaylor release [23.3.1 is ready](https://github.com/Sage-Bionetworks/data_curator/releases/tag/v23.3.1) containing exactly the same content as this PR

**Comment by adamjtaylor** [comment]
Thank you! For transparency I will scrap this PR and open one directly from the release

**Comment by adamjtaylor** [comment]
@afwillia Would you be able to resolve the conflicts in the PR for me? I can't get it to work through GH Desktop or the CLI. Thank you

**Comment by afwillia** [comment]
@adamjtaylor Yes, I just did. FYI I created a new branch for the commit which the PR automatically updated to.

**Pull request merged**
